name: CI

on:
  push:
    branches: [main, next]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'scripts/**'
      - 'test/**'
      - '*.md'
      - '*.json'
      - '*.js'
      - '*.lock'
      - 'IapExample/src/**'
      - 'IapExample/*.json'
      - 'IapExample/*.js'
      - 'IapExample/*.lock'
      - 'IapExample/*.tsx'
      - .github/**

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'scripts/**'
      - 'test/**'
      - '*.md'
      - '*.json'
      - '*.js'
      - '*.lock'
      - 'IapExample/src/**'
      - 'IapExample/*.json'
      - 'IapExample/*.js'
      - 'IapExample/*.lock'
      - 'IapExample/*.tsx'
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install modules
        run: bun install --immutable


      # - name: Install node_modules for `IapExample/`
      #   run: yarn install --immutable
      #   working-directory: IapExample

      # - name: Run TypeScript
      #   run: |
      #     yarn lint:tsc | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error -tee
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run lint scripts
      #   run: yarn lint:ci

